class AutomatedEmailPreviewRenderer
  RenderedEmail = Data.define(:subject, :recipients, :body, :error)

  NAME = '[nom du demandeur]'.freeze
  APPLICANT_EMAIL = '[email du demandeur]'.freeze
  INSTRUCTOR_EMAIL = '[email de l’instructeur]'.freeze
  RESPONSABLE_EMAIL = '[email du responsable de traitement]'.freeze
  DELEGUE_EMAIL = '[email du délégué à la protection des données]'.freeze
  ADMIN_EMAIL = '[email de l’administrateur métier]'.freeze
  ORGANIZATION = '[nom de l’organisation]'.freeze
  REQUEST_ID = '[numéro de la demande]'.freeze
  REQUEST_NAME = '[nom de la démarche]'.freeze
  MESSAGE = '[message de l’instructeur]'.freeze
  DENIAL_REASON = '[motif du refus]'.freeze
  CHANGES = '[modifications demandées]'.freeze
  REVOCATION_REASON = '[motif de la révocation]'.freeze
  CONTACT_GIVEN_NAME = '[prénom du contact]'.freeze
  CONTACT_FAMILY_NAME = '[nom du contact]'.freeze
  SCOPE_LABEL = '[périmètre de données]'.freeze
  SERVICE_PROVIDER = '[nom du fournisseur de service]'.freeze
  LINKED_ID = '[numéro de l’habilitation FranceConnect associée]'.freeze
  LINK = '[lien vers la demande]'.freeze

  Applicant = Data.define(:full_name, :email, :id)
  Org = Data.define(:name)
  ReasonHolder = Data.define(:reason)
  MessageHolder = Data.define(:message)
  ServiceProviderHolder = Data.define(:name)
  RequestHolder = Data.define(:request)
  LinkedAuthorization = Data.define(:request, :formatted_id)
  AuthorizationHolder = Data.define(:applicant, :request, :request_as_validated, :message, :formatted_id)

  ModificationRequestHolder = Data.define(:reason) do
    def present?
      false
    end
  end

  def initialize(authorization_definition, email)
    @authorization_definition = authorization_definition
    @email = email
  end

  def call
    message = mailer_delivery.message

    RenderedEmail.new(subject: message.subject, recipients: message[:to]&.value, body: body_from(message), error: nil)
  rescue StandardError => e
    Sentry.capture_exception(e)

    RenderedEmail.new(subject: nil, recipients: nil, body: nil, error: "#{e.class}: #{e.message}")
  end

  private

  def mailer_delivery
    deliveries[@email.mailer]&.call
  end

  def deliveries # rubocop:disable Metrics/AbcSize
    {
      'AuthorizationRequestMailer' => -> { AuthorizationRequestMailer.with(authorization_request: request).public_send(@email.action) },
      'Instruction::AuthorizationRequestMailer' => -> { Instruction::AuthorizationRequestMailer.with(authorization_request: request, user: instructor).public_send(@email.action) },
      'GDPRContactMailer' => -> { GDPRContactMailer.with(authorization_request: request).public_send(@email.action) },
      'FranceConnectMailer' => -> { FranceConnectMailer.with(authorization_request: request).new_scopes },
      'AutoGeneratedFranceConnectMailer' => -> { auto_generated_delivery },
      'DGFIP::APIMMailer' => -> { DGFIP::APIMMailer.with(authorization:, reopening: reopening?).approve },
      'HubEEMailer' => -> { HubEEMailer.with(authorization_request: request).administrateur_metier(hubee_kind) },
    }
  end

  def auto_generated_delivery
    if @email.action == 'new_scopes'
      AutoGeneratedFranceConnectMailer.with(authorization_request: request, linked_authorization: linked_authorization).new_scopes
    else
      AutoGeneratedFranceConnectMailer.with(authorization: authorization, api_particulier_authorization_request: request).public_send(@email.action)
    end
  end

  def request
    @request ||= build_request
  end

  def build_request
    @authorization_definition.authorization_request_class.new.tap do |req|
      stub_identity(req)
      stub_workflow(req)
      stub_contacts(req)
    end
  end

  def stub_identity(req)
    stub(req, id: 0, persisted?: true, to_param: 'exemple', formatted_id: REQUEST_ID,
      name: REQUEST_NAME, applicant: applicant, organization: Org.new(name: ORGANIZATION),
      scopes: [SCOPE_LABEL], last_submitted_at: Time.zone.now)
  end

  def stub_workflow(req)
    stub(req, reopening?: reopening?, latest_authorization: MessageHolder.new(message: MESSAGE),
      denial: ReasonHolder.new(reason: DENIAL_REASON),
      modification_request: ModificationRequestHolder.new(reason: CHANGES),
      revocation: ReasonHolder.new(reason: REVOCATION_REASON),
      france_connect_authorization: RequestHolder.new(request: req),
      service_provider: ServiceProviderHolder.new(name: SERVICE_PROVIDER))
  end

  def stub_contacts(req)
    stub(req, responsable_traitement_given_name: CONTACT_GIVEN_NAME,
      delegue_protection_donnees_given_name: CONTACT_GIVEN_NAME,
      responsable_traitement_email: RESPONSABLE_EMAIL, delegue_protection_donnees_email: DELEGUE_EMAIL,
      administrateur_metier_given_name: CONTACT_GIVEN_NAME,
      administrateur_metier_family_name: CONTACT_FAMILY_NAME, administrateur_metier_email: ADMIN_EMAIL)
  end

  def stub(object, methods)
    methods.each { |name, value| object.define_singleton_method(name) { value } }
  end

  def applicant
    @applicant ||= Applicant.new(full_name: NAME, email: APPLICANT_EMAIL, id: 0)
  end

  def instructor
    @instructor ||= Applicant.new(full_name: NAME, email: INSTRUCTOR_EMAIL, id: 0)
  end

  def authorization
    AuthorizationHolder.new(applicant: applicant, request:, request_as_validated: request, message: MESSAGE, formatted_id: REQUEST_ID)
  end

  def linked_authorization
    LinkedAuthorization.new(request:, formatted_id: LINKED_ID)
  end

  def hubee_kind
    @authorization_definition.id.delete_prefix('hubee_').to_sym
  end

  def reopening?
    @email.state[:reopening] == true
  end

  def body_from(message)
    part = message.text_part || message

    sanitize_links(part.body.decoded).strip
  end

  def sanitize_links(text)
    text.gsub(%r{https?://\S+}) { |url| url.include?('hubee.numerique.gouv.fr') ? url : LINK }
  end
end
