class DeliverLinkedFranceConnectRevocationNotification < ApplicationInteractor
  def call
    linked_fc_authorizations.each do |authorization|
      AutoGeneratedFranceConnectMailer.with(
        authorization:
      ).revoke.deliver_later
    end
  end

  private

  def linked_fc_authorizations
    context.authorization_request.authorizations
      .where(authorization_request_class: 'AuthorizationRequest::FranceConnect')
  end
end
