class DeliverLinkedFranceConnectNotification < ApplicationInteractor
  def call
    return if context.linked_france_connect_authorization.blank?

    deliver_applicant_email
    deliver_fc_support_email if should_notify_fc_support?
  end

  private

  delegate :authorization_request, :linked_france_connect_authorization, to: :context, private: true

  def deliver_applicant_email
    AutoGeneratedFranceConnectMailer.with(
      authorization: linked_france_connect_authorization
    ).approve.deliver_later
  end

  def deliver_fc_support_email
    AutoGeneratedFranceConnectMailer.with(
      authorization_request:,
      linked_authorization: linked_france_connect_authorization
    ).new_scopes.deliver_later
  end

  def should_notify_fc_support?
    return true unless authorization_request.reopening?

    api_particulier_scopes_changed?
  end

  def api_particulier_scopes_changed?
    previous = previous_api_particulier_authorization
    return true if previous.nil?

    normalize_scopes(previous.data['scopes']) != normalize_scopes(authorization_request.scopes)
  end

  def normalize_scopes(scopes)
    return [] if scopes.blank?

    parsed = scopes.is_a?(String) ? JSON.parse(scopes) : scopes
    Array(parsed).sort
  rescue JSON::ParserError
    Array(scopes).sort
  end

  def previous_api_particulier_authorization
    authorization_request.authorizations
      .where(authorization_request_class: authorization_request.class.name)
      .where.not(id: context.authorization&.id)
      .order(created_at: :desc)
      .first
  end
end
