require 'simplecov'

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

DatabaseCleaner.allow_remote_database_url = true

Cucumber::Rails::Database.autorun_database_cleaner = false

World(FactoryBot::Syntax::Methods)

Seeds.new.flushdb

Before('@javascript') do
  ActiveRecord::Base.connection_pool.pin_connection!(true)
end

Before do
  DatabaseCleaner.strategy = :transaction
  DatabaseCleaner.clean
  DatabaseCleaner.start
  Kredis.redis.flushdb
end

After do
  Capybara.reset_sessions!
  DatabaseCleaner.clean
  ActiveRecord::Base.connection_pool.unpin_connection! if javascript?
  AuthorizationDefinition.reset!
  AuthorizationRequestForm.reset!
end

ActiveJob::Base.queue_adapter = :test

Bullet.add_safelist type: :unused_eager_loading, class_name: 'AuthorizationRequest', association: :authorizations
AuthorizationRequestForm.all.map(&:authorization_request_class).each do |klass|
  Bullet.add_safelist type: :unused_eager_loading, class_name: klass.to_s, association: :authorizations
end
