api_particulier:
  name: "API Particulier"
  description: "Entités administratives, simplifiez les démarches des particuliers en récupérant pour eux leurs informations administratives (quotient familial CAF, composition familiale, statut demandeur d’emploi, étudiant et étudiant boursier)."
  cgu_link: "https://particulier.api.gouv.fr/cgu"
  provider: "dinum"
  link: "https://api.gouv.fr/les-api/api-particulier"
  access_link: https://particulier.api.gouv.fr/compte/jetons/%{external_provider_id}
  kind: 'api'
  public: true
  blocks:
    - name: "basic_infos"
    - name: "modalities"
    - name: "personal_data"
    - name: "legal"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: "Quotient familial CAF & MSA"
      value: "cnaf_quotient_familial"
      group: "API Quotient familial CAF & MSA"
    - name: "Identités allocataire et conjoint"
      value: "cnaf_allocataires"
      group: "API Quotient familial CAF & MSA"
    - name: "Identités enfants"
      value: "cnaf_enfants"
      group: "API Quotient familial CAF & MSA"
    - name: "Adresse du foyer"
      value: "cnaf_adresse"
      group: "API Quotient familial CAF & MSA"

    - name: "Statut demandeur d'emploi et identité"
      value: "pole_emploi_identite"
      group: "API Statut demandeur d'emploi"
    - name: "Téléphones et e-mail"
      value: "pole_emploi_contact"
      group: "API Statut demandeur d'emploi"
    - name: "Adresse"
      value: "pole_emploi_adresse"
      group: "API Statut demandeur d'emploi"
    - name: "Données d'inscription France Travail"
      value: "pole_emploi_inscription"
      group: "API Statut demandeur d'emploi"

    - name: "Montants et dates des paiements France Travail"
      value: "pole_emploi_paiements"
      group: "API Paiements France Travail"

    - name: "Statut élève scolarisé et identité"
      value: "men_statut_scolarite"
      group: "API Statut élève scolarisé et boursier"
    - name: "Statut boursier (disponible en 2025)"
      value: "men_statut_boursier"
      group: "API Statut élève scolarisé et boursier"
    - name: "Échelon de la bourse (disponible en 2025)"
      value: "men_echelon_bourse"
      group: "API Statut élève scolarisé et boursier"

    - name: "Statut étudiant boursier"
      value: "cnous_statut_boursier"
      group: "API Statut étudiant boursier"
    - name: "Échelon de la bourse"
      value: "cnous_echelon_bourse"
      group: "API Statut étudiant boursier"
    - name: "Identité"
      value: "cnous_identite"
      group: "API Statut étudiant boursier"
    - name: "E-mail"
      value: "cnous_email"
      group: "API Statut étudiant boursier"
    - name: "Période de versement"
      value: "cnous_periode_versement"
      group: "API Statut étudiant boursier"
    - name: "Statut définitif de la bourse"
      value: "cnous_statut_bourse"
      group: "API Statut étudiant boursier"
    - name: "Ville d‘études et établissement"
      value: "cnous_ville_etudes"
      group: "API Statut étudiant boursier"

    - name: "Identité de l'étudiant"
      value: "mesri_identite"
      group: "API Statut étudiant"
    - name: 'Statut étudiant "admis"'
      value: "mesri_admission"
      group: "API Statut étudiant"
    - name: "Statut étudiant inscrit | Périmètre formation initiale"
      value: "mesri_inscription_etudiant"
      group: "API Statut étudiant"
    - name: "Statut étudiant inscrit | Périmètre formation continue"
      value: "mesri_inscription_autre"
      group: "API Statut étudiant"
    - name: "Liste des établissements"
      value: "mesri_etablissements"
      group: "API Statut étudiant"

    - name: "Statut C2S"
      value: "complementaire_sante_solidaire"
      group: "API Complémentaire Santé Solidaire"

    - name: "Statut RSA"
      value: "revenu_solidarite_active"
      group: "API Revenue de Solidarité Active"
    - name: "Majoration RSA"
      value: "revenu_solidarite_active_majoration"
      group: "API Revenue de Solidarité Active"

    - name: "Statut Prime d'activité"
      value: "prime_activite"
      group: "API Prime d'Activité"
    - name: "Majoration Prime d'activité"
      value: "prime_activite_majoration"
      group: "API Prime d'Activité"

    - name: "Statut ASF"
      value: "allocation_soutien_familial"
      group: "API Allocation Soutien Familial"

    - name: "Statut AAH"
      value: "allocation_adulte_handicape"
      group: "API Allocation Adulte Handicapé"

formulaire_qf:
  name: Formulaire d'accès au Quotient Familial
  description: "Accéder au quotient familial CAF & MSA pour simplifier la tarification sociale municipale à l'enfance par le biais du \"formulaire de collecte du quotient familial\" et du portail agent HubEE."
  provider: "dinum"
  kind: 'service'
  link: "https://quotient-familial.numerique.gouv.fr/"
  cgu_link: "https://quotient-familial.numerique.gouv.fr/cgu_administrations"
  access_link: "https://quotient-familial.numerique.gouv.fr/"
  public: false
  blocks:
    - name: "legal"
    - name: "contacts"


