france_connect:
  name: France Connect
  description: "Identifier les utilisateurs de votre site internet et accéder à certaines données d'identité certifiées."
  provider: "dinum"
  kind: 'service'
  link: "https://franceconnect.gouv.fr/"
  cgu_link: "https://franceconnect.gouv.fr/mentions-legales"
  support_email: "support.partenaires@franceconnect.gouv.fr"
  public: true
  blocks:
    - name: "basic_infos"
    - name: "personal_data"
    - name: "legal"
    - name: "france_connect_eidas"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: "Nom de naissance"
      value: "family_name"
      group: "Identité pivot"
    - name: "Prénoms"
      value: "given_name"
      group: "Identité pivot"
    - name: "Date de naissance"
      value: "birthdate"
      group: "Identité pivot"
    - name: "Ville de naissance"
      value: "birthplace"
      group: "Identité pivot"
    - name: "Pays de naissance"
      value: "birthcountry"
      group: "Identité pivot"
    - name: "Sexe"
      value: "gender"
      group: "Identité pivot"
    - name: "Nom d'usage"
      value: "preferred_username"
      group: "Autres données"
    - name: "Adresse électronique"
      value: "email"
      group: "Autres données"
    - name: "Identifiant technique"
      value: "openid"
      group: "Données techniques"
      included: true


