api_captchetat:
  name: "API CaptchEtat"
  description: "Générer un CAPTCHA pour sécuriser un service en ligne"
  public: true
  kind: 'api'
  link: "https://api.gouv.fr/les-api/api-captchetat"
  cgu_link: "/cgus/cgu_api_captchetat_v_1_2.pdf"
  support_email: "piste.aife@finances.gouv.fr"
  provider: "aife"
  blocks:
    - name: "basic_infos"
    - name: "contacts"

api_pro_sante_connect:
  name: "API Pro Santé Connect"
  description: "Authentifier les professionnels de la santé à partir du Répertoire Partagé des Professionnels de Santé (RPPS)."
  public: true
  kind: 'api'
  link: "https://api.gouv.fr/les-api/api-pro-sante-connect"
  cgu_link: "https://industriels.esante.gouv.fr/produits-et-services/pro-sante-connect/conditions-generale-d-utilisation-pro-sante-connect"
  support_email: "prosanteconnect.editeurs@esante.gouv.fr"
  provider: "ans"
  blocks:
    - name: "basic_infos"
    - name: "legal"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: "Identifiant national"
      value: "idnat"
      group: "Données"
    - name: "Données sectorielles"
      value: "donnees_sectorielles"
      group: "Données"

annuaire_des_entreprises:
  name: "Espace agent de l'Annuaire des Entreprises"
  description: "Permet de consulter des données d'entreprises réservées aux agents de l'administration, certaines de ces données étant sous habilitation."
  provider: "dinum"
  kind: 'service'
  link: "https://annuaire-entreprises.data.gouv.fr/"
  cgu_link: "https://annuaire-entreprises.data.gouv.fr/cgu"
  access_link: "https://annuaire-entreprises.data.gouv.fr/compte"
  support_email: "support@annuaire-entreprises.data.gouv.fr"
  public: true
  blocks:
    - name: "basic_infos"
    - name: "legal"
    - name: "scopes"
  scopes:
    - name: "Effectifs annuels"
      group: "Données générales"
      value: "effectifs_annuels"
    - name: "Chiffre d'affaires"
      group: "Données financières"
      value: "chiffre_affaires"
    - name: "Bilans Banque de France"
      group: "Données financières"
      value: "bilans_bdf"
    - name: "Liasses fiscales"
      group: "Données financières"
      value: "liasses_fiscales"
    - name: "Attestations de conformité fiscale et sociale"
      group: "Données financières"
      value: "conformite"
    - name: "Certifications travaux publics"
      group: "Données travaux publics"
      value: "travaux_publics"
    - name: "Liens capitalistiques"
      group: "Données sur les bénéficiaires effectifs et le capital"
      value: "liens_capitalistiques"
    - name: "Bénéficiaires effectifs"
      group: "Données sur les bénéficiaires effectifs et le capital"
      value: "beneficiaires"
