produits_dinum:
  name: "Produits DINUM"
  description: "Ce formulaire est destiné aux administrations qui souhaitent accéder aux produits du catalogue DINUM. Ce formulaire vous permet de choisir les produits auxquels vous souhaitez avoir accès."
  provider: "dinum"
  kind: 'service'
  cgu_link: "https://example.org/cgu-produits-dinum"
  support_email: "support@yopmail.com"
  public: true
  blocks:
    - name: "legal"
    - name: "contacts"
