services_cisirh:
  name: Services et applications fournis par le CISIRH
  description: Le CISIRH contribue à la modernisation de la fonction "ressources humaines" de l’État dans les domaines métiers et applicatifs.
  provider: "cisirh"
  kind: 'service'
  link: "https://services-cisirh.gouv.fr/feedme-with-valid-url"
  cgu_link: "https://services-cisirh.gouv.fr/cgu"
  access_link: "https://services-cisirh.gouv.fr/tokens/%{external_provider_id}"
  public: true
  support_email: "api.cisirh@finances.gouv.fr"
  blocks:
    - name: "basic_infos"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: "Gestion administrative (GA)"
      value: "gestion_administrative"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Préliquidation (PLQ)"
      value: "preliquidation"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Congés absences"
      value: "conges_absence"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Module formation"
      value: "formation"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Congés annuels et télétravail"
      value: "conges_annuels"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Mobilité"
      value: "mobilite"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Self classique"
      value: "self_classique"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Compétences"
      value: "competences"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Self mobile (RIE)"
      value: "self_mobile"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Sas RenoiRH"
      value: "sas"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "GAUdDi (dossier individuel et comptable de l'agent)"
      value: "gauddi"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Interface compte individuel retraite (CIR)"
      value: "compte_individuel_retraite"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Validé signé déposé (VSD) et fond de dossier"
      value: "vsd"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Interface SOCLE RH (mise à disposition de l'extraction des données)"
      value: "socle_rh"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "RenoiRH Décisionnel (Pilotage des RH)/RenoiRH Dataviz (prochainement disponible)"
      value: "decisionnel"
      group: "Ecosystème RenoiRH - Services de base"
    - name: "Module GTA (badgeages, gestion des temps et activités – horaires variables)"
      value: "gestion_temps_activites"
      group: "Ecosystème RenoiRH - Services optionnels (coût additionnel)"
    - name: "Module API (interface de programmation)"
      value: "api_module"
      group: "Ecosystème RenoiRH - Services optionnels (coût additionnel)"
    - name: "Module Gestion des moyens"
      value: "gestion_moyens"
      group: "Ecosystème RenoiRH - Services optionnels (coût additionnel)"
    - name: "GPS applicatif"
      value: "gps"
      group: "Ecosystème RenoiRH - Services optionnels (coût additionnel)"
    - name: "Moteur indemnitaire"
      value: "moteur_indemnitaire"
      group: "Ecosystème RenoiRH - Services optionnels (coût additionnel)"
    - name: "Signature électronique"
      value: "signature_electronique"
      group: "Ecosystème RenoiRH - Services optionnels (coût additionnel)"
    - name: "ESTEVE (évaluation des agents)"
      value: "esteve"
      group: "Autres services RH"
    - name: "RenoiRH-Paie (paie directe des établissement publics)"
      value: "renoirh_paie"
      group: "Autres services RH"
    - name: "SICARDI (viviers et compétences des agents de l'Etat)"
      value: "sicardi"
      group: "Autres services RH"
    - name: "RIGA (suivi des mouvement sociaux)"
      value: "riga"
      group: "Autres services RH"
    - name: "Arrêt de travail - Maladie professionnelle (AT-MP) - A venir"
      value: "at_mp"
      group: "Autres services RH"
    - name: "INGRES (référentiels RH interministériels)"
      value: "ingres"
      group: "Autres services RH"
    - name: "REBECCA (assistant conversationnel destiné aux gestionnaires RH)"
      value: "rebecca"
      group: "Autres services RH"
    - name: "Visualisation des fichiers PAY/PAYSAGE"
      value: "pay_paysage"
      group: "Autres services RH"

