class AutoGeneratedFranceConnectMailer < ApplicationMailer
  def approve
    @authorization = params[:authorization]
    @authorization_request = @authorization.request_as_validated
    @service_provider = params[:api_particulier_authorization_request].service_provider

    mail(
      to: @authorization.applicant.email,
      subject: t('.subject', authorization_request_id: @authorization.request.id)
    )
  end

  def revoke
    @authorization = params[:authorization]
    @authorization_request = @authorization.request_as_validated

    mail(
      to: @authorization.applicant.email,
      subject: t('.subject', authorization_request_id: @authorization.request.id)
    )
  end

  def new_scopes
    @authorization_request = params[:authorization_request]
    @linked_authorization = params[:linked_authorization]

    mail(
      to: 'support.partenaires@franceconnect.gouv.fr',
      subject: new_scopes_subject,
      from: 'datapass@api.gouv.fr',
      cc: 'equipe-datapass@api.gouv.fr'
    )
  end

  private

  def new_scopes_subject
    "[DataPass] nouveaux scopes pour \"#{@authorization_request.organization.name} - #{@authorization_request.id}\""
  end
end
