require 'rails_helper'

RSpec.describe DeliverLinkedFranceConnectNotification do
  describe '#call' do
    subject(:interactor) { described_class.call(context_params) }

    let(:authorization_request) do
      create(:authorization_request, :api_particulier, :with_france_connect_embedded_fields, :validated, fill_all_attributes: true)
    end
    let(:authorization) { authorization_request.latest_authorization }
    let(:linked_france_connect_authorization) do
      create(
        :authorization,
        request: authorization_request,
        applicant: authorization_request.applicant,
        authorization_request_class: 'AuthorizationRequest::FranceConnect',
        data: authorization_request.france_connect_attributes.transform_keys(&:to_s)
      )
    end
    let(:context_params) do
      {
        authorization_request:,
        authorization:,
        linked_france_connect_authorization:
      }
    end

    context 'when linked_france_connect_authorization is present' do
      it 'delivers an approval email to the applicant' do
        expect { interactor }
          .to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :approve)
      end

      it 'delivers a new_scopes email to FC support' do
        expect { interactor }
          .to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :new_scopes)
      end
    end

    context 'when linked_france_connect_authorization is blank' do
      let(:linked_france_connect_authorization) { nil }

      it 'does not deliver any emails' do
        expect { interactor }
          .not_to have_enqueued_mail(AutoGeneratedFranceConnectMailer)
      end
    end

    context 'when it is a reopening' do
      before do
        authorization_request.update!(
          last_validated_at: 1.day.ago,
          reopened_at: 1.hour.ago,
          state: 'submitted'
        )
      end

      context 'when API Particulier scopes have changed' do
        let!(:previous_authorization) do
          create(
            :authorization,
            request: authorization_request,
            applicant: authorization_request.applicant,
            authorization_request_class: authorization_request.class.name,
            data: { 'scopes' => %w[cnaf_quotient_familial] },
            created_at: 2.days.ago
          )
        end

        before do
          authorization_request.update!(scopes: %w[cnaf_quotient_familial cnaf_allocataires])
        end

        it 'delivers the FC support email' do
          expect { interactor }
            .to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :new_scopes)
        end
      end

      context 'when API Particulier scopes have NOT changed' do
        let!(:previous_authorization) do
          create(
            :authorization,
            request: authorization_request,
            applicant: authorization_request.applicant,
            authorization_request_class: authorization_request.class.name,
            data: { 'scopes' => authorization_request.scopes },
            created_at: 2.days.ago
          )
        end

        it 'does NOT deliver the FC support email' do
          expect { interactor }
            .not_to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :new_scopes)
        end

        it 'still delivers the applicant email' do
          expect { interactor }
            .to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :approve)
        end
      end
    end
  end
end
