require 'rails_helper'

RSpec.describe DeliverLinkedFranceConnectRevocationNotification do
  describe '#call' do
    subject(:interactor) { described_class.call(authorization_request:) }

    let(:authorization_request) do
      create(:authorization_request, :api_particulier, :with_france_connect_embedded_fields, :revoked, fill_all_attributes: true)
    end

    context 'when there are linked FranceConnect authorizations' do
      let!(:linked_fc_authorization) do
        create(
          :authorization,
          request: authorization_request,
          applicant: authorization_request.applicant,
          authorization_request_class: 'AuthorizationRequest::FranceConnect',
          data: authorization_request.france_connect_attributes.transform_keys(&:to_s),
          revoked: true
        )
      end

      it 'delivers revoke email for each linked FC authorization' do
        expect { interactor }
          .to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :revoke)
      end

      context 'with multiple linked FC authorizations' do
        let!(:another_fc_authorization) do
          create(
            :authorization,
            request: authorization_request,
            applicant: authorization_request.applicant,
            authorization_request_class: 'AuthorizationRequest::FranceConnect',
            data: authorization_request.france_connect_attributes.transform_keys(&:to_s),
            revoked: true
          )
        end

        it 'delivers revoke email for each linked FC authorization' do
          expect { interactor }
            .to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :revoke).exactly(2).times
        end
      end
    end

    context 'when there are no linked FranceConnect authorizations' do
      it 'does not deliver any emails' do
        expect { interactor }
          .not_to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :revoke)
      end
    end

    context 'when there is only an API Particulier authorization' do
      let!(:api_particulier_authorization) do
        create(
          :authorization,
          request: authorization_request,
          applicant: authorization_request.applicant,
          authorization_request_class: authorization_request.class.name,
          revoked: true
        )
      end

      it 'does not deliver any emails for non-FC authorizations' do
        expect { interactor }
          .not_to have_enqueued_mail(AutoGeneratedFranceConnectMailer, :revoke)
      end
    end
  end
end
