new_api_names = {
"AuthorizationRequest::APICprProAdelie":"CPR PRO",
"AuthorizationRequest::APIEContacts":"E-Contacts",
"AuthorizationRequest::APIENSUDocuments":"Ensu documents",
"AuthorizationRequest::APIEPro":"E-PRO",
"AuthorizationRequest::APIFicoba":"Ficoba",
"AuthorizationRequest::APIHermes":"Hermès",
"AuthorizationRequest::APIImpotParticulier":"Impôt particulier",
"AuthorizationRequest::APIINFINOE":"Infinoe",
"AuthorizationRequest::APIMire":"Mire",
"AuthorizationRequest::APIOcfi":"OCFI",
"AuthorizationRequest::APIOpale":"Opale",
"AuthorizationRequest::APIR2P":"R2P",
"AuthorizationRequest::APIRial":"RIAL",
"AuthorizationRequest::APIRobf":"ROBF",
"AuthorizationRequest::APISFiP":"SFiP",
"AuthorizationRequest::APISatelit":"Satelit",

"AuthorizationRequest::APICprProAdelieSandbox":"CPR PRO",
"AuthorizationRequest::APIEContactsSandbox":"E-Contacts",
"AuthorizationRequest::APIENSUDocumentsSandbox":"Ensu documents",
"AuthorizationRequest::APIEProSandbox":"E-PRO",
"AuthorizationRequest::APIFicobaSandbox":"Ficoba",
"AuthorizationRequest::APIHermesSandbox":"Hermès",
"AuthorizationRequest::APIImpotParticulierSandbox":"Impôt particulier",
"AuthorizationRequest::APIINFINOESandbox":"Infinoe",
"AuthorizationRequest::APIMireSandbox":"Mire",
"AuthorizationRequest::APIOcfiSandbox":"OCFI",
"AuthorizationRequest::APIOpaleSandbox":"Opale",
"AuthorizationRequest::APIR2PSandbox":"R2P",
"AuthorizationRequest::APIRialSandbox":"RIAL",
"AuthorizationRequest::APIRobfSandbox":"ROBF",
"AuthorizationRequest::APISFiPSandbox":"SFiP",
"AuthorizationRequest::APISatelitSandbox":"Satelit"
}