---
shared:
  portail-hubee-demarche-certdc:
    authorization_request: 'HubEECertDC'
  api-entreprise:
    authorization_request: 'APIEntreprise'
    steps:
      - name: 'basic_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'scopes'
      - name: 'contacts'
  api-infinoe-sandbox:
    authorization_request: 'APIInfinoeSandbox'
    steps:
      - name: 'basic_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'contacts'

  api-infinoe-production:
    authorization_request: 'APIInfinoeProduction'
