---
shared:
  portail-hubee-demarche-certdc:
    name: "Portail HubEE - Démarche CertDC"
    description: "Certificats de Décès"
    public: true
    authorization_request: 'HubEECertDC'
    logo: 'hubee.png'
    templates:
      template1:
        name: Template 1
        attributes:
          intitule: Intitulé 1
      template2:
        name: Template 2
        attributes:
          intitule: Intitulé 2
          administrateur_metier_family_name: Dupont
          administrateur_metier_given_name: Jean
          administrateur_metier_email: dupont.jean@gouv.fr
          administrateur_metier_phone_number: '0336656565'
          administrateur_metier_job_title: Directeur
