---
shared:
  portail-hubee-demarche-certdc:
    authorization_request: 'HubEECertDC'

  api-entreprise:
    name: "Demande libre"
    default: true
    description: "Pour les utilisateurs expérimentés qui connaissent précisemment l'usage des données et les aspects techniques des APIs"
    authorization_request: 'APIEntreprise'
    steps:
      - name: 'basic_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'scopes'
      - name: 'contacts'

  api-entreprise-marches-publics:
    name: "Marchés publics"
    description: "Facilitez le dépôt des candidatures et récupérez les justificatifs administratifs de vos utilisateurs."
    use_case: 'marches_publics'
    authorization_request: 'APIEntreprise'
    steps:
      - name: 'basic_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'scopes'
      - name: 'contacts'

  api-entreprise-aides-publiques:
    name: "Aides publiques"
    description: "Faciliter le dépôt et l'instruction des aides publiques"
    use_case: 'aides_publiques'
    authorization_request: 'APIEntreprise'
    steps:
      - name: 'basic_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'scopes'
      - name: 'contacts'

  api-entreprise-mgdis:
    name: "Solution Portail des aides de l'éditeur MGDIS"
    description: "Solution logicielle fournie par l'éditeur MGDIS."
    use_case: 'aides_publiques'
    authorization_request: 'APIEntreprise'
    editor_id: 'mgdis'
    data:
      intitule: "Solution Portail des aides de l'éditeur MGDIS"
      description: "Dans un objectif de dématérialisation des aides publiques, nous mettons en place un outil, à destination des usagers de notre organisme leur permettant de déposer des demandes d’aides/subventions, qui seront ensuite instruites par nos agents dans ce même outil.
La demande d’accès à API Entreprise est effectuée dans le but de faciliter le dépôt et l’instruction des demandes d’aides publiques pour les entreprises et associations du territoire, et de récupérer les justificatifs administratifs de ces organisations demandant des aides publiques, sans avoir à les demander aux demandeurs d’aides.

La plateforme, mise en place pour permettre le dépôt de ces aides publiques et l’instruction de ces demandes, s’appuie sur la solution « Portail des Aides » de l’éditeur MGDIS."
      scopes:
        - unites_legales_etablissements_insee
        - associations_djepva
        - mandataires_sociaux_infogreffe
        - attestation_fiscale_dgfip
        - attestation_sociale_urssaf
      destinataire_donnees_caractere_personnel: Agents instructeurs des aides publiques
      duree_conservation_donnees_caractere_personnel: 36
      cadre_juridique_nature: "Décret n° 2019-31 du 18 janvier 2019 relatif aux échanges d’informations et de données entre administrations dans le cadre des démarches administratives et à l’expérimentation prévue par l’article 40 de la loi n° 2018-727 du 10 août 2018 pour un Etat au service d’une société de confiance"
      cadre_juridique_url: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000038029589/"

      contact_technique_given_name: &api_entreprise_mgdis_contact_given_name 'Jean-Michel'
      contact_technique_family_name: &api_entreprise_mgdis_contact_family_name 'Dupont'
      contact_technique_job_title: &api_entreprise_mgdis_contact_job_title 'Chef de projet'
      contact_technique_email: &api_entreprise_mgdis_contact_email 'assistance@mgdis.fr'
      contact_technique_phone_number: &api_entreprise_mgdis_contact_phone_number '0297681828'

      contact_metier_given_name: *api_entreprise_mgdis_contact_given_name
      contact_metier_family_name: *api_entreprise_mgdis_contact_family_name
      contact_metier_job_title: *api_entreprise_mgdis_contact_job_title
      contact_metier_email: *api_entreprise_mgdis_contact_email
      contact_metier_phone_number: *api_entreprise_mgdis_contact_phone_number

  api-entreprise-setec-atexo:
    name: "Dématérialisation des marchés publics"
    description: "Solution logicielle fournie par l'éditeur Setec."
    authorization_request: 'APIEntreprise'
    use_case: 'marches_publics'
    editor_id: 'setec'
    data:
      intitule: "Outil de dématérialisation des appels d’offres des marchés publics - Solution LOCAL TRUST MPE via SETEC"
      description: |+
        Cette demande sous entend que vous avez fait appel à la société SETEC 702 005 901 00104 pour le traitement de vos marchés publics à travers la plateforme LOCAL TRUST MPE de Atexo.

        Afin de faciliter cette investigation du marché fournisseurs, ATEXO propose le module de Sourcing. Combiné au profil acheteur MPE, il permet aux entreprises de mettre en avant leurs informations.

        Basé sur l’open data et les renseignements des entreprises, ce module présente aux acheteurs des fiches fournisseurs complètes : établissements, éléments financiers, contrats publics, références significatives, expertises, contacts qualifiés, etc.
      scopes:
        - unites_legales_etablissements_insee
        - associations_djepva
        - effectifs_urssaf
        - mandataires_sociaux_infogreffe
        - chiffre_affaires_dgfip
        - attestation_fiscale_dgfip
        - attestation_sociale_urssaf
        - cotisations_msa
        - cotisations_probtp
        - certification_cnetp

      destinataire_donnees_caractere_personnel: Acheteurs publics dans le cadre de leur activité de traitement des marchés publics
      duree_conservation_donnees_caractere_personnel: 36
      cadre_juridique_nature: |+
        Service numérique de conformité pour les administrations publiques dans le cadre du décret N°2011-1601 et de l’article D8222 du code du travail, offre de services d’intermédiation aux organismes publics, tel que défini par l’article 17, alinéa IV, du décret du 24 septembre 2014 et le décret lié à la commande publique n° 2016-360.
        https://www.legifrance.gouv.fr/codes/id/LEGIARTI000018520702/2011-12-31/

        Article R2143-13 du code de la commande publique. Concernant l’accès des acheteurs aux documents justificatifs et moyens de preuve.
        https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037730589
      cadre_juridique_url: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000018520702/2011-12-31/

      contact_technique_email: &api_entreprise_setec_atexo_contact_email "<%= Rails.application.credentials.api_entreprise_setec_atexo_contact_email || 'not_valid@setec.com' %>"
      contact_technique_phone_number: &api_entreprise_setec_atexo_contact_phone_number "<%= Rails.application.credentials.api_entreprise_setec_atexo_contact_phone_number || '0836656565' %>"

      contact_metier_email: *api_entreprise_setec_atexo_contact_email
      contact_metier_phone_number: *api_entreprise_setec_atexo_contact_phone_number

  api-particulier:
    name: "Demande libre"
    default: true
    authorization_request: 'APIParticulier'
    steps:
      - name: 'basic_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'scopes'
      - name: 'contacts'

  api-infinoe-sandbox:
    authorization_request: 'APIInfinoeSandbox'
    steps:
      - name: 'basic_infos'
      - name: 'legal'
      - name: 'contacts'

  api-infinoe-production:
    authorization_request: 'APIInfinoeProduction'

  api-service-national-inscription-concours-examen:
    name: "Inscription à un concours ou un examen (hors permis de conduire)"
    authorization_request: 'APIServiceNational'
    data:
      intitule: "Inscription à un concours ou un examen (hors permis de conduire)"
      description: "La candidature à un concours ou examens en France nécessite souvent l'inscription à un service national. Ce service permet au candidat d'être identifié et authentifié de manière sécurisée lors de son inscription."
      destinataire_donnees_caractere_personnel:
      duree_conservation_donnees_caractere_personnel: "12"
      cadre_juridique_nature: "Article L114-6 du code du service national"
      cadre_juridique_url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000021960309/"

  api-service-national-obligation-service-national:
    name: "Accès à un statut exigeant d’être en règle avec les obligations de service national"
    authorization_request: 'APIServiceNational'
    data:
      intitule: "Accès à un statut exigeant d’être en règle avec les obligations de service national"
      description:
      destinataire_donnees_caractere_personnel:
      duree_conservation_donnees_caractere_personnel: "12"
      cadre_juridique_nature: "Article L111-3 du code du service national"
      cadre_juridique_url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000024042593/"

  api-service-national:
    name: "Demande libre"
    authorization_request: 'APIServiceNational'
    steps:
      - name: 'minimal_infos'
      - name: 'personal_data'
      - name: 'legal'
      - name: 'contacts'

  api-captchetat:
    authorization_request: 'APICaptchEtat'
    steps:
      - name: 'basic_infos'
      - name: 'legal'
      - name: 'contacts'
