---
shared:
  hubee:
    name: HubEE
    logo: hubee.png
    link: https://hubee.numerique.gouv.fr/
  dinum:
    name: DINUM
    logo: dinum.png
    link: https://www.numerique.gouv.fr/
  dgfip:
    name: DGFIP
    logo: dgfip.jpeg
    link: https://api.gouv.fr/producteurs/dgfip
  ministere_des_armees:
    name: MinistereDesArmees
    logo: minarm.jpg
    link: https://api.gouv.fr/les-api/api-service-national
