---
shared:
  dgs:
    name: Organisation de la direction générale de la santé (DGS)
    logo: ministere_sante.jpg
    link: https://www.sante.gouv.fr/
  dila:
    name: Direction de l'information légale et administrative (DILA)
    logo: dila_premier_ministre.jpg
    link: https://www.dila.premier-ministre.gouv.fr/
  dinum:
    name: DINUM
    logo: dinum.png
    link: https://www.numerique.gouv.fr/
  dgfip:
    name: DGFIP
    logo: dgfip.jpeg
    link: https://api.gouv.fr/producteurs/dgfip
  ministere_des_armees:
    name: Ministere Des Armees
    logo: minarm.jpg
    link: https://api.gouv.fr/les-api/api-service-national
  aife:
    name: Agence pour l'Information Financière de l'État
    logo: aife.jpeg
    link: https://aife.economie.gouv.fr/
