default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'data_pass_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'data_pass_test' } %>
