---
shared:
  mgdis:
    name: MGDIS
    siret: '32816124500027'
  setec:
    name: SETEC
    siret: '70200590100104'
  e_attestations:
    name: e-Attestations
    siret: '50382936800045'
  provigis:
    name: Provigis
    siret: '43196025100061'
  achat_solution:
    name: Achat Solution
    siret: '81449011600013'
  atexo:
    name: Atexo
    siret: '44090956200033'

  aiga:
    name: Aiga
    siret: '39825361700045'
  abelium:
    name: Abelium Collectivités
    siret: '42172024400050'
  agora_plus:
    name: Agora Plus
    siret: '48017088500010'
  amiciel:
    name: Amiciel
    siret: '44884396100013'
  arpege:
    name: Arpège
    siret: '35142130000036'
  berger_levrault:
    name: Berger-Levrault
    siret: '75580064600373'
  jdealise:
    name: JDéalise
    siret: '89255569900016'
  arche_mc2:
    name: Arche MC2
    siret: '38251931200088'
  afi:
    name: Agence Française d'Informatique (AFI)
    siret: '32275019100031'
  mushroom_software:
    name: Mushroom Software
    siret: '81122842800017'
  ciril_group:
    name: Ciril GROUP
    siret: '30516304000119'
  cosoluce:
    name: Cosoluce
    siret: '44321098400052'
  docaposte:
    name: DOCAPOSTE
    siret: '48847870200035'
  entrouvert:
    name: Entrouvert
    siret: '49108189900032'
  jvs_mairistem:
    name: JVS-Mairistem
    siret: '32855218700069'
  nfi:
    name: Nord France Informatique
    siret: '37996323400032'
  odyssee_informatique:
    name: Odyssée Informatique
    siret: '38812677300026'
  qiis:
    name: Qiis
    siret: '52834311400021'
  sigec:
    name: SIGEC
    siret: '33307306200015'
  teamnet:
    name: Teamnet
    siret: '33922000600078'
  technocarte:
    name: Technocarte
    siret: '38873581300056'
  waigeo:
    name: Waigeo
    siret: '80321944300014'
  3d_ouest:
    name: 3D Ouest
    siret: '44973625500018'
  coexya:
    name: Coexya
    siret: '43362470700017'
