development:
  rails_pulse_summary:
    cron: '5 * * * *'
    class: 'RailsPulse::SummaryJob'
  rails_pulse_cleanup:
    cron: '0 3 * * *'
    class: 'RailsPulse::CleanupJob'

staging: &deployed
  healthcheck:
    cron: '*/5 * * * *'
    class: 'HealthcheckJob'
  rails_pulse_summary:
    cron: '5 * * * *'
    class: 'RailsPulse::SummaryJob'
  rails_pulse_cleanup:
    cron: '0 3 * * *'
    class: 'RailsPulse::CleanupJob'

production:
  <<: *deployed
  datagouv_habilitations_sync:
    cron: '0 2 1 * *'
    class: 'DatagouvHabilitationsSyncJob'

sandbox: *deployed
