module Stats
  class Aggregator
    def initialize(authorization_requests=nil)
      @authorization_requests = authorization_requests || AuthorizationRequest.all
    end

    def average_time_to_submit
      authorizations_with_first_create_and_submit_events.average("EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time))")
    end

    def min_time_to_submit
      authorizations_with_first_create_and_submit_events.minimum("EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time))")
    end

    def max_time_to_submit
      authorizations_with_first_create_and_submit_events.maximum("EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time))")
    end

    def first_create_events_subquery
      first_event_subquery('create')
    end

    def time_to_submit_by_type
      results = authorizations_with_first_create_and_submit_events
        .group("authorization_requests.type")
        .order(Arel.sql("AVG(EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time)))"))
        .pluck(
          Arel.sql("authorization_requests.type"),
          Arel.sql("MIN(EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time)))"),
          Arel.sql("AVG(EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time)))"),
          Arel.sql("MAX(EXTRACT(EPOCH FROM (first_submit_events.event_time - first_create_events.event_time)))"),
          Arel.sql("COUNT(*)")
        )
      
      results.map do |type, min_time, avg_time, max_time, count|
        {
          type: type,
          min_time: min_time&.to_f,
          avg_time: avg_time&.to_f,
          max_time: max_time&.to_f,
          count: count
        }
      end
    end

    private

    def first_submit_events_subquery
      # We ignore the legacy AuthorizationRequestChangelog as they are inconsistent data generated by the migration from v1
      first_event_subquery('submit')
        .joins("LEFT JOIN authorization_request_changelogs ON authorization_request_events.entity_type = 'AuthorizationRequestChangelog' AND authorization_request_events.entity_id = authorization_request_changelogs.id")
        .where("authorization_request_changelogs.legacy IS NULL OR authorization_request_changelogs.legacy = false")
    end

    def first_event_subquery(event_name)
      AuthorizationRequestEvent
        .where(name: event_name)
        .where.not(authorization_request_id: nil)
        .group("authorization_request_events.authorization_request_id")
        .select("authorization_request_events.authorization_request_id, MIN(authorization_request_events.created_at) as event_time")
    end

    def authorizations_with_first_create_and_submit_events
      @authorization_requests
        .joins("INNER JOIN (#{first_create_events_subquery.to_sql}) first_create_events ON first_create_events.authorization_request_id = authorization_requests.id")
        .joins("INNER JOIN (#{first_submit_events_subquery.to_sql}) first_submit_events ON first_submit_events.authorization_request_id = authorization_requests.id")
        .where("first_submit_events.event_time >= first_create_events.event_time") # we have one case where the submit event is before the create event, so we need to filter it out
    end
  end
end
