class AutoGeneratedFranceConnectMailerPreview < ActionMailer::Preview
  def approve
    AutoGeneratedFranceConnectMailer.with(
      authorization:,
      api_particulier_authorization_request: authorization_request
    ).approve
  end

  def revoke
    AutoGeneratedFranceConnectMailer.with(authorization:).revoke
  end

  def new_scopes
    AutoGeneratedFranceConnectMailer.with(
      authorization_request:,
      linked_authorization: authorization
    ).new_scopes
  end

  private

  def authorization
    Authorization.where(authorization_request_class: 'AuthorizationRequest::FranceConnect').last
  end

  def authorization_request
    AuthorizationRequest::APIParticulier.where(state: :validated).last
  end
end
