require 'rails_helper'

RSpec.describe AutoGeneratedFranceConnectMailer do
  describe '#approve' do
    subject(:mail) do
      described_class.with(
        authorization:,
        api_particulier_authorization_request: authorization_request
      ).approve
    end

    around do |example|
      ServiceProvider.find('aiga').apipfc_enabled = true
      example.run
    ensure
      ServiceProvider.find('aiga').apipfc_enabled = false
    end

    let(:authorization_request) do
      create(:authorization_request, :api_particulier_aiga, :with_france_connect_embedded_fields, :validated)
    end
    let(:authorization) do
      create(
        :authorization,
        request: authorization_request,
        applicant: authorization_request.applicant,
        authorization_request_class: 'AuthorizationRequest::FranceConnect',
        data: authorization_request.france_connect_attributes.transform_keys(&:to_s)
      )
    end

    it 'sends email to the applicant' do
      expect(mail.to).to eq([authorization_request.applicant.email])
    end

    it 'has the correct subject' do
      expect(mail.subject).to include(authorization_request.id.to_s)
      expect(mail.subject).to include('FranceConnect')
    end

    it 'renders the body with service provider name' do
      expect(mail.body.encoded).to include(authorization_request.service_provider.name)
    end

    it 'includes the full documentation link' do
      expect(mail.body.encoded).to include('docs.partenaires.franceconnect.gouv.fr')
    end

    it 'includes production key request instructions' do
      expect(mail.body.encoded).to include('demarche.numerique.gouv.fr/commencer/demande-creation-fs-fc')
    end
  end

  describe '#revoke' do
    subject(:mail) { described_class.with(authorization:).revoke }

    let(:authorization_request) do
      create(:authorization_request, :api_particulier, :with_france_connect_embedded_fields, :revoked)
    end
    let(:authorization) do
      create(
        :authorization,
        request: authorization_request,
        applicant: authorization_request.applicant,
        authorization_request_class: 'AuthorizationRequest::FranceConnect',
        data: authorization_request.france_connect_attributes.transform_keys(&:to_s)
      ).tap(&:revoke!)
    end

    it 'sends email to the applicant' do
      expect(mail.to).to eq([authorization_request.applicant.email])
    end

    it 'has the correct subject' do
      expect(mail.subject).to include(authorization_request.id.to_s)
      expect(mail.subject).to include('révoquée')
    end

    it 'renders the body with revocation reason' do
      expect(mail.body.encoded).to include(authorization_request.revocation.reason)
    end
  end

  describe '#new_scopes' do
    subject(:mail) do
      described_class.with(
        authorization_request:,
        linked_authorization:
      ).new_scopes
    end

    let(:authorization_request) do
      create(:authorization_request, :api_particulier, :with_france_connect_embedded_fields, :validated)
    end
    let(:linked_authorization) do
      create(
        :authorization,
        request: authorization_request,
        applicant: authorization_request.applicant,
        authorization_request_class: 'AuthorizationRequest::FranceConnect',
        data: authorization_request.france_connect_attributes.transform_keys(&:to_s)
      )
    end

    it 'sends email to FC support' do
      expect(mail.to).to eq(['support.partenaires@franceconnect.gouv.fr'])
    end

    it 'CCs the DataPass team' do
      expect(mail.cc).to eq(['equipe-datapass@api.gouv.fr'])
    end

    it 'has the correct subject with organization name' do
      expect(mail.subject).to include(authorization_request.organization.name)
      expect(mail.subject).to include(authorization_request.id.to_s)
    end

    it 'includes the linked authorization formatted ID' do
      expect(mail.body.encoded).to include(linked_authorization.formatted_id)
    end

    it 'includes the API Particulier scopes' do
      authorization_request.scopes.each do |scope|
        expect(mail.body.encoded).to include(scope)
      end
    end

    context 'when the request is a reopening' do
      before do
        authorization_request.update!(last_validated_at: 1.day.ago, reopened_at: 1.hour.ago, state: 'submitted')
      end

      it 'uses reopening wording' do
        expect(mail.body.encoded).to include('mise à jour')
      end
    end
  end
end
