class AuthorizationDefinition::AutomatedEmails
  Email = Data.define(:mailer, :action, :state) do
    def to_s
      "#{mailer}##{action}"
    end
  end

  EventEmails = Data.define(:event, :emails)

  EVENTS = %w[submit approve request_changes refuse revoke].freeze

  def initialize(authorization_definition)
    @authorization_definition = authorization_definition
  end

  def all
    EVENTS.map { |event| EventEmails.new(event:, emails: emails_for(event)) }
  end

  private

  def emails_for(event)
    case notifier_family
    when :entreculier then entreculier_emails(event)
    when :hubee then hubee_emails(event)
    else base_emails(event)
    end
  end

  def base_emails(event)
    case event
    when 'submit' then submit_emails
    when 'approve' then approve_emails
    when 'revoke' then [applicant_email('revoke')]
    else reopening_variants('AuthorizationRequestMailer', event)
    end
  end

  def entreculier_emails(event)
    case event
    when 'submit' then submit_emails
    when 'approve' then gdpr_emails + france_connect_emails
    else []
    end
  end

  def hubee_emails(event)
    return base_emails(event) unless event == 'approve'

    base_emails(event) + [always(mailer: 'HubEEMailer', action: 'administrateur_metier')]
  end

  def submit_emails
    reopening_variants('AuthorizationRequestMailer', 'submit') +
      reopening_variants('Instruction::AuthorizationRequestMailer', 'submit')
  end

  def approve_emails
    reopening_variants('AuthorizationRequestMailer', 'approve') +
      gdpr_emails + dgfip_emails + france_connect_emails
  end

  def reopening_variants(mailer, action)
    [
      Email.new(mailer:, action:, state: { reopening: false }),
      Email.new(mailer:, action: "reopening_#{action}", state: { reopening: true }),
    ]
  end

  def applicant_email(action)
    always(mailer: 'AuthorizationRequestMailer', action:)
  end

  def gdpr_emails
    gdpr_contacts.map { |contact| always(mailer: 'GDPRContactMailer', action: contact.to_s) }
  end

  def dgfip_emails
    return [] unless dgfip_provider?

    [always(mailer: 'DGFIP::APIMMailer', action: 'approve')]
  end

  def france_connect_emails
    return [] unless france_connect_capable?

    france_connect_state = conditional_france_connect? ? { with_france_connect: true } : {}
    [Email.new(mailer: 'FranceConnectMailer', action: 'new_scopes', state: france_connect_state)] +
      embedded_france_connect_emails
  end

  def embedded_france_connect_emails
    return [] unless embeds_france_connect_fields?

    %w[approve new_scopes].map do |action|
      Email.new(mailer: 'AutoGeneratedFranceConnectMailer', action:, state: { embeds_france_connect_fields: true })
    end
  end

  def always(mailer:, action:)
    Email.new(mailer:, action:, state: {})
  end

  def gdpr_contacts
    return [] unless authorization_request_class.respond_to?(:contact_types)

    authorization_request_class.contact_types & AuthorizationExtensions::GDPRContacts::NAMES
  end

  def dgfip_provider?
    @authorization_definition.provider&.slug == 'dgfip'
  end

  def france_connect_capable?
    authorization_request_class.include?(AuthorizationExtensions::FranceConnect)
  end

  def conditional_france_connect?
    authorization_request_class.include?(AuthorizationExtensions::Modalities)
  end

  def embeds_france_connect_fields?
    authorization_request_class.include?(AuthorizationExtensions::FranceConnectEmbeddedFields)
  end

  def notifier_family
    return :entreculier if notifier_class <= APIEntreculierNotifier
    return :hubee if notifier_class <= HubEENotifier

    :base
  end

  def notifier_class
    "#{authorization_request_class.name.demodulize}Notifier".constantize
  rescue NameError
    BaseNotifier
  end

  def authorization_request_class
    @authorization_definition.authorization_request_class
  end
end
