# Demandes libres
api-sfip-sandbox:
  name: Demande libre (Bac à sable)
  public: true
  default: true
  description: Pour les utilisateurs ayant besoin de réaliser une recette fonctionnelle en environnement de bac à sable.
  introduction: &api_sfip_sandbox_form_introduction |
    Notre équipe d’instruction étudiera votre demande en bac à sable, lorsqu’elle sera validée vous pourrez compléter la suite de votre demande.

    <div class="intro-stepper">
      <div class="step current">
        <div class="step-number">1.</div>
        <div class="step-content">
          <h3>Le bac à sable</h3>
          <p class="fr-text--xs">Dans un premier temps, une demande d’habilitation au <strong>bac à sable</strong> de l'API Impôt particulier</p>
        </div>
      </div>

      <div class="step pending">
        <div class="step-number">2.</div>
        <div class="step-content">
          <h3>La production</h3>
          <p class="fr-text--xs">Dans un second temps, une demande d’habilitation à la <strong>production</strong> de l'API Impôt particulier</p>
        </div>
      </div>

      <div class="step pending">
        <div class="step-number">3.</div>
        <div class="step-content">
          <h3>Votre service est ouvert !</h3>
          <p class="fr-text--xs">Une fois vos habilitations validées, vous pouvez ouvrir votre service !</p>
        </div>
      </div>
    </div>
  authorization_request: APISFiPSandbox
  steps: &api_sfip_sandbox_steps
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: scopes
    - name: contacts

api-sfip-production:
  name: Demande libre (Production)
  public: false
  startable_by_applicant: false
  introduction: &api_sfip_production_form_introduction |
    Votre demande d'accès au bac à sable a été validée, vous pouvez à présent poursuivre votre demande en demandant les accès à la production.

    <div class="intro-stepper">
      <div class="step completed">
        <div class="step-number">1.</div>
        <div class="step-content">
          <h3>Le bac à sable</h3>
          <p class="fr-text--xs">Dans un premier temps, une demande d’habilitation au <strong>bac à sable</strong> de l'API Impôt particulier</p>
        </div>
      </div>

      <div class="step current">
        <div class="step-number">2.</div>
        <div class="step-content">
          <h3>La production</h3>
          <p class="fr-text--xs">Dans un second temps, une demande d’habilitation à la <strong>production</strong> de l'API Impôt particulier</p>
        </div>
      </div>

      <div class="step pending">
        <div class="step-number">3.</div>
        <div class="step-content">
          <h3>Votre service est ouvert !</h3>
          <p class="fr-text--xs">Une fois vos habilitations validées, vous pouvez ouvrir votre service !</p>
        </div>
      </div>
    </div>
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: &api_sfip_production_steps
    - name: operational_acceptance
    - name: safety_certification
    - name: volumetrie

api-sfip-editeur:
  name: Demande libre avec éditeur
  public: true
  default: true
  description: Pour les utilisateurs travaillant avec un éditeur ayant déjà effectué une recette fonctionnelle.
  introduction: &api_sfip_editor_form_introduction |
    Votre éditeur a déjà obtenu l'accès à la sandbox, vous n'avez plus qu'à obtenir l'accès en production via ce formulaire.
  authorization_request: APISFiP
  steps: &api_sfip_editor_steps
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: scopes
    - name: contacts
    - name: safety_certification
    - name: volumetrie

# Stationnement résidentiel
api-sfip-stationnement-residentiel-sandbox:
  name: Stationnement résidentiel (Bac à sable)
  public: true
  use_case: stationnement_residentiel
  description: Dites-le nous une fois - Stationnement Résidentiel (Bac à sable)
  introduction: *api_sfip_sandbox_form_introduction
  authorization_request: APISFiPSandbox
  steps: *api_sfip_sandbox_steps
  data:
    intitule: Dites-le nous une fois - Stationnement Résidentiel
    description: |
      Simplification des demandes de carte de stationnement résidentiel pour les usagers par l’utilisation des données fiscales fournies par la DGFiP.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de carte de stationnement résidentiel
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

api-sfip-stationnement-residentiel-production:
  name: Stationnement résidentiel
  public: false
  startable_by_applicant: false
  use_case: stationnement_residentiel
  introduction: *api_sfip_production_form_introduction
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: *api_sfip_production_steps

api-sfip-stationnement-residentiel-editeur:
  name: Stationnement résidentiel (avec Éditeur)
  public: true
  use_case: stationnement_residentiel
  description: Dites-le nous une fois - Stationnement Résidentiel (avec Éditeur)
  authorization_request: APISFiP
  introduction: *api_sfip_editor_form_introduction
  steps: *api_sfip_editor_steps
  data:
    intitule: Dites-le nous une fois - Stationnement Résidentiel
    description: |
      Simplification des demandes de carte de stationnement résidentiel pour les usagers par l’utilisation des données fiscales fournies par la DGFiP.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de carte de stationnement résidentiel
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

# Place en crèche
api-sfip-place-creche-sandbox:
  name: Place en crèche (Bac à sable)
  public: true
  use_case: place_creche
  description: Dites-le nous une fois - Place en crèche (Bac à sable)
  introduction: *api_sfip_sandbox_form_introduction
  authorization_request: APISFiPSandbox
  steps: *api_sfip_sandbox_steps
  data:
    intitule: Dites-le nous une fois - Place en crèche
    description: |
      Simplification des demandes de place en crèche pour les usagers par l’utilisation des données fiscales fournies par la DGFiP.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de place en crèche
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

api-sfip-place-creche-production:
  name: Place en crèche
  public: false
  startable_by_applicant: false
  use_case: place_creche
  introduction: *api_sfip_production_form_introduction
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: *api_sfip_production_steps

api-sfip-place-creche-editeur:
  name: Place en crèche (avec Éditeur)
  public: true
  use_case: place_creche
  description: Dites-le nous une fois - Place en crèche (avec Éditeur)
  introduction: *api_sfip_editor_form_introduction
  authorization_request: APISFiP
  steps: *api_sfip_editor_steps
  data:
    intitule: Dites-le nous une fois - Place en crèche
    description: |
      Simplification des demandes de place en crèche pour les usagers par l’utilisation des données fiscales fournies par la DGFiP.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de place en crèche
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

# Activités périscolaires
api-sfip-activites-periscolaires-sandbox:
  name: Activités périscolaires (Bac à sable)
  public: true
  use_case: activites_periscolaires
  description: Dites-le nous une fois - Activités périscolaires (Bac à sable)
  introduction: *api_sfip_sandbox_form_introduction
  authorization_request: APISFiPSandbox
  steps: *api_sfip_sandbox_steps
  data:
    intitule: Dites-le-nous une fois – Activités périscolaires et assimilés
    description: |
      Simplification de la souscription aux activités périscolaires pour les usagers par l’utilisation des données fiscales fournies par la DGFiP afin de déterminer les tarifs applicables.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de souscription aux activités périscolaires
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

api-sfip-activites-periscolaires-production:
  name: Activités périscolaires
  public: false
  startable_by_applicant: false
  use_case: activites_periscolaires
  introduction: *api_sfip_production_form_introduction
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: *api_sfip_production_steps

api-sfip-activites-periscolaires-editeur:
  name: Activités périscolaires (avec Éditeur)
  public: true
  use_case: activites_periscolaires
  description: Dites-le nous une fois - Activités périscolaires (avec Éditeur)
  introduction: *api_sfip_editor_form_introduction
  authorization_request: APISFiP
  steps: *api_sfip_editor_steps
  data:
    intitule: Dites-le-nous une fois – Activités périscolaires et assimilés
    description: |
      Simplification de la souscription aux activités périscolaires pour les usagers par l’utilisation des données fiscales fournies par la DGFiP afin de déterminer les tarifs applicables.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de souscription aux activités périscolaires
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

# Cantine scolaire
api-sfip-cantine-scolaire-sandbox:
  name: Cantine scolaire (Bac à sable)
  public: true
  use_case: cantine_scolaire
  description: Dites-le nous une fois - Cantine scolaire (Bac à sable)
  introduction: *api_sfip_sandbox_form_introduction
  authorization_request: APISFiPSandbox
  steps: *api_sfip_sandbox_steps
  data:
    intitule: Dites-le-nous une fois – Cantine scolaire
    description: |
      Simplification de la souscription à la cantine scolaire pour les usagers par l’utilisation des données fiscales fournies par la DGFiP afin de déterminer les tarifs applicables.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de souscription à la cantine scolaire
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

api-sfip-cantine-scolaire-production:
  name: Cantine scolaire
  public: false
  startable_by_applicant: false
  introduction: *api_sfip_production_form_introduction
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: *api_sfip_production_steps

api-sfip-cantine-scolaire-editeur:
  name: Cantine scolaire (avec Éditeur)
  public: true
  use_case: cantine_scolaire
  description: Dites-le nous une fois - Cantine scolaire (avec Éditeur)
  introduction: *api_sfip_editor_form_introduction
  authorization_request: APISFiP
  steps: *api_sfip_editor_steps
  data:
    intitule: Dites-le-nous une fois – Cantine scolaire
    description: |
      Simplification de la souscription à la cantine scolaire pour les usagers par l’utilisation des données fiscales fournies par la DGFiP afin de déterminer les tarifs applicables.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de souscription à la cantine scolaire
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

# Aides sociales facultatives
api-sfip-aides-sociales-facultatives-sandbox:
  name: Aides sociales facultatives (Bac à sable)
  public: true
  use_case: subventions_associations
  description: Dites-le nous une fois - Aides sociales facultatives (Bac à sable)
  introduction: *api_sfip_sandbox_form_introduction
  authorization_request: APISFiPSandbox
  steps: *api_sfip_sandbox_steps
  data:
    intitule: Dites-le-nous une fois – Aides sociales facultatives
    description: |
      Simplification des demandes d’aides sociales facultatives pour les usagers par l’utilisation des données fiscales fournies par la DGFiP pour déterminer l’éligibilité au service.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes d’aides sociales facultatives
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

api-sfip-aides-sociales-facultatives-production:
  name: Aides sociales facultatives
  public: false
  startable_by_applicant: false
  introduction: *api_sfip_production_form_introduction
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: *api_sfip_production_steps

api-sfip-aides-sociales-facultatives-editeur:
  name: Aides sociales facultatives (avec Éditeur)
  public: true
  use_case: subventions_associations
  description: Dites-le nous une fois - Aides sociales facultatives (avec Éditeur)
  introduction: *api_sfip_editor_form_introduction
  authorization_request: APISFiP
  steps: *api_sfip_editor_steps
  data:
    intitule: Dites-le-nous une fois – Aides sociales facultatives
    description: |
      Simplification des demandes d’aides sociales facultatives pour les usagers par l’utilisation des données fiscales fournies par la DGFiP pour déterminer l’éligibilité au service.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes d’aides sociales facultatives
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

# Carte de transport
api-sfip-carte-transport-sandbox:
  name: Carte de transport (Bac à sable)
  public: true
  use_case: carte_transport
  description: Dites-le nous une fois - Carte de transport (Bac à sable)
  introduction: *api_sfip_sandbox_form_introduction
  authorization_request: APISFiPSandbox
  steps: *api_sfip_sandbox_steps
  data:
    intitule: Dites-le-nous une fois – Carte de transport
    description: |
      Simplification de la souscription à la carte de transport pour les usagers par l’utilisation des données fiscales fournies par la DGFiP pour déterminer le tarif applicable.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de carte de transport
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)

api-sfip-carte-transport-production:
  name: Carte de transport
  public: false
  startable_by_applicant: false
  introduction: *api_sfip_production_form_introduction
  authorization_request: APISFiP
  static_blocks: *api_sfip_sandbox_steps
  steps: *api_sfip_production_steps

api-sfip-carte-transport-editeur:
  name: Carte de transport (avec Éditeur)
  public: true
  use_case: carte_transport
  description: Dites-le nous une fois - Carte de transport (avec Éditeur)
  introduction: *api_sfip_editor_form_introduction
  authorization_request: APISFiP
  steps: *api_sfip_editor_steps
  data:
    intitule: Dites-le-nous une fois – Carte de transport
    description: |
      Simplification de la souscription à la carte de transport pour les usagers par l’utilisation des données fiscales fournies par la DGFiP pour déterminer le tarif applicable.
      (A compléter par le demandeur)
    destinataire_donnees_caractere_personnel: Agents instructeurs des demandes de carte de transport
    cadre_juridique_nature: |
      - Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016, relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données (RGPD)
      - Les articles L. 114-8 et suivants du code des relations entre le public et l’administration (CRPA)
      - Délibération de la collectivité (ou autre fondement juridique)
