api-gfe-echange-editeurs-restauration:
  description: Permet aux éditeurs de transmettre leur flux XML quotidien contenant les repas consommés ou réservés des élèves.
  introduction: |
    Cette API permet aux éditeurs de transmettre leur flux XML quotidien contenant les repas consommés ou réservés des élèves.
  authorization_request: APIGFEEchangeEditeursRestauration
  steps:
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: contacts
