api-gfe-echange-collectivites:
  description: Permet aux collectivités de récupérer les élèves d'un établissement puis de transmettre leur flux XML contenant les tranches des élèves.
  introduction: |
    Cette API permet aux collectivités de récupérer les élèves d'un établissement puis de transmettre leur flux XML contenant les tranches des élèves.
  authorization_request: APIGFEEchangeCollectivites
  steps:
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: contacts
