api-impot-particulier-sandbox:
  description: TODO
  introduction: |
    Ceci est une introduction à remplir
  authorization_request: APIImpotParticulierSandbox
  steps: &api_impot_particulier_sandbox_steps
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: scopes
    - name: contacts

api-impot-particulier:
  description: TODO
  introduction: |
    Votre éditeur a déjà obtenu l'accès à la sandbox, vous n'avez plus qu'à obtenir l'accès en production via ce formulaire.
  authorization_request: APIImpotParticulier
  static_blocks: *api_impot_particulier_sandbox_steps
  steps:
    - name: operational_acceptance
    - name: safety_certification
    - name: volumetrie

api-impot-particulier-editeur:
  name: API Impôt Particulier avec éditeur
  description: TODO
  introduction: |
    Votre éditeur a déjà obtenu l'accès à la sandbox, vous n'avez plus qu'à obtenir l'accès en production via ce formulaire.
  authorization_request: APIImpotParticulier
  steps:
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: scopes
    - name: contacts
    - name: operational_acceptance
    - name: safety_certification
    - name: volumetrie

