api-rial-sandbox:
  description: FEED ME
  introduction: |
    <strong>Mode de fonctionnement de l’API Rial</strong>
    </br>
    L’API restitue toutes les données sans restrictions. Vous pouvez consulter notre documentation qui vous permettra de comprendre le fonctionnement de notre API ainsi que les données que nous proposons.
    </br>
    <a href="documentation_api_rial_v2024_11-1.pdf", target="_blank">Voir la documentation de l’API Rial</a>
    </br>
    </br>

    Notre équipe d’instruction étudiera votre demande en bac à sable, lorsqu’elle sera validée vous pourrez compléter la suite de votre demande.

    <div class="intro-stepper">
      <div class="step current">
        <div class="step-number">1.</div>
        <div class="step-content">
          <h3>Le bac à sable</h3>
          <p class="fr-text--xs">Dans un premier temps, une demande d’habilitation au <strong>bac à sable</strong> de l'API Rial</p>
        </div>
      </div>

      <div class="step pending">
        <div class="step-number">2.</div>
        <div class="step-content">
            <h3>La production</h3>
            <p class="fr-text--xs">Dans un second temps, une demande d’habilitation à la <strong>production</strong> de l'API Rial</p>
        </div>
      </div>

        <div class="step pending">
          <div class="step-number">3.</div>
          <div class="step-content">
            <h3>Votre service est ouvert !</h3>
            <p class="fr-text--xs">Une fois vos habilitations validées, vous pouvez ouvrir votre service !</p>
          </div>
        </div>
      </div>
  authorization_request: APIRialSandbox
  steps: &api_rial_steps
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: contacts

api-rial-production:
  description: FEED ME
  startable_by_applicant: false
  introduction: |
    Votre demande d'accès au bac à sable a été validée, vous pouvez à présent poursuivre votre demande en demandant les accès à la production.

    <div class="intro-stepper">
      <div class="step completed">
        <div class="step-number">1.</div>
        <div class="step-content">
          <h3>Le bac à sable</h3>
          <p class="fr-text--xs">Dans un premier temps, une demande d’habilitation au <strong>bac à sable</strong> de l'API Rial</p>
        </div>
      </div>

      <div class="step current">
        <div class="step-number">2.</div>
        <div class="step-content">
          <h3>La production</h3>
          <p class="fr-text--xs">Dans un second temps, une demande d’habilitation à la <strong>production</strong> de l'API Rial</p>
        </div>
      </div>

      <div class="step pending">
        <div class="step-number">3.</div>
        <div class="step-content">
          <h3>Votre service est ouvert !</h3>
          <p class="fr-text--xs">Une fois vos habilitations validées, vous pouvez ouvrir votre service !</p>
        </div>
      </div>
    </div>
  authorization_request: APIRial
  static_blocks: *api_rial_steps
  steps:
    - name: operational_acceptance
    - name: safety_certification
    - name: volumetrie
