pro-connect-fs: &pro_connect_common
  authorization_request: ProConnectServiceProvider
  steps:
    - name: basic_infos
    - name: personal_data
    - name: legal
    - name: scopes
    - name: modalities
    - name: contacts
  data:
    cadre_juridique_nature: "La décision n°DINUM-202106-01 du 1er juin 2021"
    cadre_juridique_url: "https://www.info.gouv.fr/sites/default/files/contenu/piece-jointe/2021/05/20210601-dinum-ac-creation_agentconnect-vf.pdf"
pro-connect-fi:
  <<: *pro_connect_common
  authorization_request: ProConnectIdentityProvider

