services-cisirh:
  description: Recueil des différents éléments tant organisationnels que techniques pour le cadrage de la relation entre le CISIRH et ses partenaires
  introduction: |
    Le présent formulaire a pour objectif de recueillir les différents éléments tant organisationnels que techniques pour le cadrage de la relation entre le CISIRH et ses partenaires.
    <br />
    <br />
    Toute utilisation d’un service du CISIRH implique l’acceptation des Conditions générales d’adhésion et des conditions générales d’utilisation des solutions du CISIRH.
  authorization_request: ServicesCisirh
  steps:
    - name: basic_infos
    - name: scopes
    - name: contacts
