RSpec.describe AuthorizationDefinition::AutomatedEmails do
  before { create(:data_provider, :dgfip) }

  def emails_for(definition_id, event)
    AuthorizationDefinition.find(definition_id).automated_emails
      .find { |event_emails| event_emails.event == event }
      .emails
  end

  def email_states(definition_id, event)
    emails_for(definition_id, event).to_h { |email| [email.to_s, email.state] }
  end

  describe '#all' do
    it 'splits reopening-aware emails into their two request states' do
      expect(email_states('annuaire_des_entreprises', 'submit')).to eq(
        'AuthorizationRequestMailer#submit' => { reopening: false },
        'AuthorizationRequestMailer#reopening_submit' => { reopening: true },
        'Instruction::AuthorizationRequestMailer#submit' => { reopening: false },
        'Instruction::AuthorizationRequestMailer#reopening_submit' => { reopening: true }
      )
    end

    it 'marks gdpr and dgfip emails as always triggered' do
      expect(email_states('api_ficoba', 'approve')).to eq(
        'AuthorizationRequestMailer#approve' => { reopening: false },
        'AuthorizationRequestMailer#reopening_approve' => { reopening: true },
        'GDPRContactMailer#responsable_traitement' => {},
        'GDPRContactMailer#delegue_protection_donnees' => {},
        'DGFIP::APIMMailer#approve' => {}
      )
    end

    it 'marks France Connect as always triggered when the request always has it' do
      expect(email_states('api_droits_cnam', 'approve')).to include(
        'FranceConnectMailer#new_scopes' => {}
      )
    end

    it 'describes the request state of conditional and embedded France Connect emails' do
      expect(email_states('api_particulier', 'approve')).to eq(
        'GDPRContactMailer#delegue_protection_donnees' => {},
        'FranceConnectMailer#new_scopes' => { with_france_connect: true },
        'AutoGeneratedFranceConnectMailer#approve' => { embeds_france_connect_fields: true },
        'AutoGeneratedFranceConnectMailer#new_scopes' => { embeds_france_connect_fields: true }
      )
    end

    it 'has no reopening variant for revoke' do
      expect(email_states('annuaire_des_entreprises', 'revoke')).to eq(
        'AuthorizationRequestMailer#revoke' => {}
      )
    end
  end

  describe '#count' do
    it 'counts one card per mailer/action pair, merging standard and reopening variants' do
      definition = AuthorizationDefinition.find('annuaire_des_entreprises')

      expect(described_class.new(definition).count).to eq(6)
    end
  end

  describe '#all against the definition_automated_emails mapping' do
    config = YAML.load_file(Rails.root.join('spec/notifiers/definition_automated_emails.yaml'), aliases: true)
    events = config['authorization_request_events']

    def self.states_for(event_config)
      event_config['authorization_request_states'] || [{ 'emails' => event_config['emails'] }]
    end

    def request_attributes(state)
      attributes = state.slice('reopening', 'with_france_connect').symbolize_keys
      return attributes unless Array(state['factory_traits']).include?('with_france_connect_embedded_fields')

      attributes.merge(with_france_connect: true, embeds_france_connect_fields: true)
    end

    def triggered_emails(definition_id, event, state)
      attributes = request_attributes(state)

      emails_for(definition_id, event)
        .select { |email| email.state.all? { |key, value| attributes.fetch(key, false) == value } }
        .map(&:to_s)
    end

    config['authorization_definitions'].each do |definition_config|
      definition_id = definition_config['definition_id'] # rubocop:disable RSpec/LeakyLocalVariable

      events.each do |event_name|
        event_config = definition_config['events'].find { |event| event['event_name'] == event_name } || {}

        states_for(event_config).each do |state_config|
          state = state_config['state'] || {} # rubocop:disable RSpec/LeakyLocalVariable
          expected_emails = state_config['emails'] || [] # rubocop:disable RSpec/LeakyLocalVariable

          it "maps every #{definition_id} #{event_name} email for request state #{state}" do
            expect(triggered_emails(definition_id, event_name, state)).to match_array(expected_emails)
          end
        end
      end
    end
  end
end
