name: Deployment via HTTPS

on:
  workflow_dispatch: ~

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        host: [watchdoge1, watchdoge2, watchdoge3, watchdoge4, watchdoge5]
    environment: sandbox
    env:
      DEPLOY_HTTPS_LOGIN: ${{ secrets.DEPLOY_HTTPS_LOGIN }}
      DEPLOY_HTTPS_PASSWORD: ${{ secrets.DEPLOY_HTTPS_PASSWORD }}
      DEPLOY_HTTPS_REQUEST_URL: ${{ vars.DEPLOY_HTTPS_REQUEST_URL }}
      DEPLOY_HTTPS_RESPONSE_URL: ${{ vars.DEPLOY_HTTPS_RESPONSE_URL }}
      DEPLOY_HOST: host_${{ matrix.host }}
      DEPLOY_APP: datapass_reborn_sandbox
    steps:
      - name: Installed dependencies
        run: sudo apt-get install -y jq curl
      - name: Generate random UUID
        run: |
          echo "DEPLOY_ID=$(uuidgen)" >>$GITHUB_ENV
      - name: Send deploy request
        shell: bash
        run: |
          curl -sSL --fail -K - -X POST -H "Content-Type: application/json" -d "{\"id\":\"$DEPLOY_ID\",\"app\":\"$DEPLOY_APP\",\"host\":\"$DEPLOY_HOST\"}" "${DEPLOY_HTTPS_REQUEST_URL}/${DEPLOY_ID}" <<<"-u \"${DEPLOY_HTTPS_LOGIN}:${DEPLOY_HTTPS_PASSWORD}\""
      - name: Wait for deploy to finish
        shell: bash
        run: |
          for I in $(seq 1 300); do
            set -e
            DEPLOY_STATUS=$(curl --fail -sSL -K - "${DEPLOY_HTTPS_RESPONSE_URL}/${DEPLOY_ID}" <<<"-u \"${DEPLOY_HTTPS_LOGIN}:${DEPLOY_HTTPS_PASSWORD}\"")
            set +e
            echo "$DEPLOY_STATUS"
            JSON_STATUS=$(echo "$DEPLOY_STATUS" | jq -r .status 2>/dev/null)
            if [ "$JSON_STATUS" == "finished" ]; then
              DEPLOY_PASS=$(echo "$DEPLOY_STATUS" | jq -r .pass)
              if [ "$DEPLOY_PASS" == "true" ]; then
                exit 0
              else
                exit 1
              fi
            fi
            sleep 1
          done
          echo Timeout
          exit 1
