name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: data_pass:latest
          outputs: type=docker,dest=/tmp/data_pass.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image and ENV file
        id: data_pass-docker
        uses: actions/cache@v3
        with:
          path: |
            /tmp/data_pass.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-data_pass

  security:
    name: "Security: Brakeman"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: |
            /tmp/data_pass.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-data_pass
      - run: docker load --input /tmp/data_pass.tar
      - run: docker run --rm --entrypoint="" data_pass:latest bundle exec brakeman

  lint:
    name: "Linting: Rubocop"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: |
            /tmp/data_pass.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-data_pass
      - run: docker load --input /tmp/data_pass.tar
      - run: docker run --rm --entrypoint="" data_pass:latest bundle exec rubocop
  tests:
    name: "Tests: RSpec"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      chrome:
        image: browserless/chrome:latest
        ports:
          - "3333:3333"
        env:
          PORT: 3333
          CONNECTION_TIMEOUT: 600000
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: |
            /tmp/data_pass.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-data_pass
      - run: docker load --input /tmp/data_pass.tar
      - run: |
          docker run \
            --network="host" \
            --env-file ./.github/workflows/test.env \
            --rm data_pass bundle exec rspec
